import "server-only";
import { fal } from "@/lib/fal/client";
import type { VoiceEngine as VoiceEngineName } from "@/generated/prisma/enums";

/**
 * Voice engines behind one interface (see docs/VOICE_PLAN.md). The rest of the
 * app never talks to MiniMax or ElevenLabs directly — swapping or adding an
 * engine touches only this file.
 */
export type CloneResult = { providerVoiceId: string; previewUrl: string | null };
export type SpeakResult = { audioUrl: string; durationMs: number | null };

export interface VoiceProviderImpl {
  /** Clone from a public sample URL; returns the engine's voice id. */
  clone(sampleAudioUrl: string, opts: { name: string; previewText: string }): Promise<CloneResult>;
  /** Generate speech with a cloned voice; returns a public audio URL. */
  speak(text: string, providerVoiceId: string): Promise<SpeakResult>;
}

export const PREVIEW_TEXT =
  "Hey! This is a quick preview of this voice, generated by Peakfinity Studio.";

// ─── MiniMax (via fal) ───────────────────────────────────────────────────────
// Clone: fal-ai/minimax/voice-clone → { custom_voice_id, audio? } — passing
// `text` makes it return a TTS preview in the same call.
// Speak:  fal-ai/minimax/speech-02-hd → { audio: { url }, duration_ms }.
// NOTE: MiniMax deletes a cloned voice if no TTS uses it for 7 days.

type MinimaxCloneOutput = {
  custom_voice_id: string;
  audio?: { url?: string } | null;
};

type MinimaxSpeechOutput = {
  audio: { url: string };
  duration_ms: number;
};

const minimax: VoiceProviderImpl = {
  async clone(sampleAudioUrl, { previewText }) {
    const { data } = await fal.subscribe("fal-ai/minimax/voice-clone", {
      input: {
        audio_url: sampleAudioUrl,
        noise_reduction: true,
        text: previewText,
        model: "speech-02-hd",
      },
    });
    const out = data as MinimaxCloneOutput;
    if (!out.custom_voice_id) throw new Error("MiniMax did not return a voice id");
    return { providerVoiceId: out.custom_voice_id, previewUrl: out.audio?.url ?? null };
  },

  async speak(text, providerVoiceId) {
    const { data } = await fal.subscribe("fal-ai/minimax/speech-02-hd", {
      input: {
        text,
        voice_setting: { voice_id: providerVoiceId, speed: 1, vol: 1, pitch: 0 },
        // Default is "hex" (inline bytes) — we need a URL.
        output_format: "url",
      },
    });
    const out = data as MinimaxSpeechOutput;
    if (!out.audio?.url) throw new Error("MiniMax TTS did not return audio");
    return { audioUrl: out.audio.url, durationMs: out.duration_ms ?? null };
  },
};

// ─── ElevenLabs (direct API) ─────────────────────────────────────────────────
// Uses the team's own account (ELEVENLABS_API_KEY), so cloned voices live in
// that account and persist — no 7-day expiry. TTS returns raw audio bytes,
// which we re-host on fal storage so downstream steps (lipsync) get a URL.

const ELEVENLABS_BASE = "https://api.elevenlabs.io";
// Verified default; "eleven_v3" can be swapped in here once confirmed working
// on the account's plan.
const ELEVENLABS_MODEL_ID = "eleven_multilingual_v2";

function elevenLabsKey(): string {
  const key = process.env.ELEVENLABS_API_KEY;
  if (!key) {
    throw new Error("ElevenLabs is not configured (ELEVENLABS_API_KEY is missing)");
  }
  return key;
}

async function elevenLabsError(res: Response, fallback: string): Promise<string> {
  try {
    const body = (await res.json()) as { detail?: { message?: string } | string };
    if (typeof body.detail === "string") return body.detail;
    if (body.detail?.message) return body.detail.message;
  } catch {
    // non-JSON body
  }
  return `${fallback} (HTTP ${res.status})`;
}

const elevenlabs: VoiceProviderImpl = {
  async clone(sampleAudioUrl, { name, previewText }) {
    const key = elevenLabsKey();

    // The sample lives on fal storage; fetch it and forward as multipart.
    const sampleRes = await fetch(sampleAudioUrl);
    if (!sampleRes.ok) throw new Error("Could not download the voice sample");
    const sampleBytes = await sampleRes.arrayBuffer();
    const contentType = sampleRes.headers.get("content-type") ?? "audio/mpeg";

    const form = new FormData();
    form.append("name", name);
    form.append("remove_background_noise", "true");
    form.append("files", new File([sampleBytes], "sample.mp3", { type: contentType }));

    const res = await fetch(`${ELEVENLABS_BASE}/v1/voices/add`, {
      method: "POST",
      headers: { "xi-api-key": key },
      body: form,
    });
    if (!res.ok) {
      throw new Error(await elevenLabsError(res, "ElevenLabs voice clone failed"));
    }
    const out = (await res.json()) as { voice_id?: string };
    if (!out.voice_id) throw new Error("ElevenLabs did not return a voice id");

    const preview = await elevenlabs.speak(previewText, out.voice_id);
    return { providerVoiceId: out.voice_id, previewUrl: preview.audioUrl };
  },

  async speak(text, providerVoiceId) {
    const key = elevenLabsKey();
    const res = await fetch(
      `${ELEVENLABS_BASE}/v1/text-to-speech/${providerVoiceId}?output_format=mp3_44100_128`,
      {
        method: "POST",
        headers: { "xi-api-key": key, "content-type": "application/json" },
        body: JSON.stringify({ text, model_id: ELEVENLABS_MODEL_ID }),
      }
    );
    if (!res.ok) {
      throw new Error(await elevenLabsError(res, "ElevenLabs TTS failed"));
    }
    // Raw MP3 bytes → re-host on fal storage for a public URL.
    const bytes = await res.arrayBuffer();
    const url = await fal.storage.upload(
      new File([bytes], "voice.mp3", { type: "audio/mpeg" })
    );
    return { audioUrl: url, durationMs: null };
  },
};

const ENGINES: Record<VoiceEngineName, VoiceProviderImpl> = {
  MINIMAX: minimax,
  ELEVENLABS: elevenlabs,
};

export function voiceEngine(provider: VoiceEngineName): VoiceProviderImpl {
  return ENGINES[provider];
}

export function engineAvailable(provider: VoiceEngineName): boolean {
  if (provider === "ELEVENLABS") return Boolean(process.env.ELEVENLABS_API_KEY);
  return Boolean(process.env.FAL_KEY);
}

/** Days until MiniMax deletes an unused clone (ElevenLabs voices persist). */
export const MINIMAX_RETENTION_DAYS = 7;
